core:
  agent_subprocesses: 20
  log_level: debug

server:
  username: switchmap
  api_bind_port: 7000
  listen_address: localhost
  ingest_interval: 86400
  purge_after_ingest: True 
  db_host: switchmap-mysql
  db_name: switchmap
  db_user: switchmap
  db_pass: CHANGE_ME_NOW
  api_listen_address: 0.0.0.0  
  api_bind_port: 7000

dashboard:
  api_listen_address: 0.0.0.0  
  api_bind_port: 7001

poller:
  username: switchmap
  polling_interval: 86400
  server_address: switchmap-api
  server_bind_port: 7000
  server_username: null
  server_password: None
  server_https: false
  zones:
    - zone: TEST
      hostnames:
        - 192.168.1.1
        - 192.168.1.2
        - 192.168.1.3
        - 192.168.1.4
  snmp_groups:

      - group_name: V2
        snmp_version: 2
        snmp_secname:
        snmp_community: Q6RNgKDntG77xseZ
        snmp_port: 161
        snmp_authprotocol:
        snmp_authpassword:
        snmp_privprotocol:
        snmp_privpassword:
        enabled: True

      - group_name: HOME
        snmp_version: 2
        snmp_secname:
        snmp_community: zYDsg7t4BqbegY6
        snmp_port: 161
        snmp_authprotocol:
        snmp_authpassword:
        snmp_privprotocol:
        snmp_privpassword:
        enabled: True

      - group_name: AUTH_PRIV_01
        snmp_version: 3
        snmp_secname: user_priv_01
        snmp_community:
        snmp_port: 161
        snmp_authprotocol: md5
        snmp_authpassword: dW97hNrL8mFkjxRT
        snmp_privprotocol: des
        snmp_privpassword: 5wjUShs8jEy9v3WE
        enabled: True

      - group_name: AUTH_PRIV_02
        snmp_version: 3
        snmp_secname: user_priv_00
        snmp_community:
        snmp_port: 161
        snmp_authprotocol: sha
        snmp_authpassword: Kj7PSgHSwCgPErxq
        snmp_privprotocol: aes
        snmp_privpassword: CdgkMAvYTd7qPWVy
        enabled: True

      - group_name: AUTH_NOPRIV
        snmp_version: 3
        snmp_secname: user_auth_00
        snmp_community:
        snmp_port: 161
        snmp_authprotocol: sha
        snmp_authpassword: 7g8aYMhS29MHJzvS
        snmp_privprotocol:
        snmp_privpassword:
        enabled: True

      - group_name: NOAUTH_NOPRIV
        snmp_version: 3
        snmp_secname: user_noauth
        snmp_community:
        snmp_port: 161
        snmp_authprotocol:
        snmp_authpassword:
        snmp_privprotocol:
        snmp_privpassword:
        enabled: True